import { Prisma, Category, Question } from '@prisma/client';

// Re-export standard model types generated by Prisma
export type { Category, Question };

// Create compound types based on our specific database queries

// Type for a category that includes its array of questions
export type CategoryWithQuestions = Prisma.CategoryGetPayload<{
  include: { 
    questions: true;
    subCategories: true;
  }
}>;

// Type for a subcategory (one level deep) with its counts
type SubCategoryWithCount = Prisma.CategoryGetPayload<{
  include: {
    _count: {
      select: { questions: true }
    }
  }
}>;

// Type for a top-level category that includes its subcategories
export type CategoryWithCounts = Prisma.CategoryGetPayload<{
  include: {
    _count: {
      select: { questions: true }
    }
  }
}> & {
  subCategories: SubCategoryWithCount[];
};

export enum DifficultyLevel {
  Easy = "Easy",
  Medium = "Medium",
  Hard = "Hard",
}
